{% set name = "pyturbo" %}
{% set version = "0.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/twiinit/pyturbo/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 65eae229f8091f0f1de95bd1748528068cae54ff4f10be7454c52a9297204ef2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - cosapp >=0.12.0
    - numpy >=1.14
    - pyoccad >=0.5.0
    - ambiance

test:
  imports:
    - pyturbo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/twiinIT/pyturbo
  summary: Turbomachinery models
  description: pyTurbo is a library for turbomachinery modeling and simulation based on CoSApp
  dev_url: https://github.com/twiinIT/pyturbo
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - adriendelsalle
